runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 3
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "creds.json"

handlers:
- url: /.*  
  script: auto
